FROM navitia/master

COPY navitia/source/sql/alembic /usr/share/navitia/ed/alembic
COPY navitia/source/sql/requirements.txt /tmp/requirements.txt
COPY navitia/source/cities /usr/share/navitia/cities
COPY instances_configuration.sh /
COPY templates/* /templates/

RUN apt-get update \
    && apt install -y python python-pip git libpq-dev postgresql-client \
    && apt-get clean

RUN pip install -r /tmp/requirements.txt

CMD sh -x /instances_configuration.sh
