FROM navitia/master

COPY navitia-common_*.deb navitia-jormungandr_*.deb ./

RUN apt-get update \
    && apt install -y curl python python-pip git libgeos-c1v5 libpq5 ./navitia-common_*.deb ./navitia-jormungandr_*.deb \
    && apt-get clean \
    && rm -rf navitia-common_*.deb navitia-jormungandr_*.deb

# install jormungandr requirements
RUN pip install --no-cache-dir -r /usr/share/jormungandr/requirements.txt \
    && pip install uwsgi

WORKDIR /usr/src/app/

HEALTHCHECK CMD curl -f http://localhost/v1/coverage || exit 1

ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=2

CMD ["uwsgi", "--master", "--lazy-apps", "--mount", "/=jormungandr:app", "--http", "0.0.0.0:80"]
